### ISSUE TITLE
seems to conflict with built-in Logger

### ISSUE THREAD

**Issue by kingsleyh** [tbrand/awesome-logger#1]
I've added deps to my project:

```
dependencies:
 awesome-logger:
    github:      tbrand/awesome-logger
```

but when I run my file:
```
require "logger"
Logger.warning("Forks.")
```

It says:
```
crystal run src/job/job.cr
Error in src/job/job.cr:3: undefined method 'warning' for Logger:Class

Logger.warning("Forks.")
```

I believe it's conflicting with the built-in logger or something?

**Comment by tbrand** [comment]
Thanks for the report. Yeah might be conflicted with https://github.com/crystal-lang/crystal/blob/master/src/logger.cr?
I've renamed it into `L`. So please use `L.warning` or `L.w` for the purpose. :+1:

**Comment by kingsleyh** [comment]
I think require "logger" is still causing an issue as that is the same require for the built-in logger - probably Logger class was fine - but maybe require "awesome-logger"

**Comment by tbrand** [comment]
Oh you are right. I've never test by using external repository. lol
I'll fix it.

**Comment by tbrand** [comment]
Done. Now please use `require "awesome-logger"`.
